version: 2
updates:
  # Enable version updates for yarn
  - package-ecosystem: "yarn"
    directory: "/"  
    schedule:
      interval: "weekly"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
